<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net10.0</TargetFrameworks>
    <OutputType>Exe</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Shouldly" />
    <PackageReference Include="Testcontainers.PostgreSql" />
    <PackageReference Include="Testcontainers.Redis" />
    <PackageReference Include="Testcontainers.KurrentDb" />
    <PackageReference Include="Testcontainers.MongoDb" />
    <PackageReference Include="Testcontainers.MsSql" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="$(CoreRoot)/Eventuous.Application/Eventuous.Application.csproj" />
    <ProjectReference Include="$(SrcRoot)/Postgres/src/Eventuous.Postgresql/Eventuous.Postgresql.csproj" />
    <ProjectReference Include="$(SrcRoot)/Redis/src/Eventuous.Redis/Eventuous.Redis.csproj" />
    <ProjectReference Include="$(SrcRoot)/KurrentDB/src/Eventuous.KurrentDB/Eventuous.KurrentDB.csproj" />
    <ProjectReference Include="$(SrcRoot)/Mongo/src/Eventuous.MongoDB/Eventuous.MongoDB.csproj" />
    <ProjectReference Include="$(SrcRoot)/SqlServer/src/Eventuous.SqlServer/Eventuous.SqlServer.csproj" />
    <ProjectReference Include="$(SrcRoot)/Core/gen/Eventuous.Shared.Generators/Eventuous.Shared.Generators.csproj" Aliases="SnapshotGenerator" />
  </ItemGroup>
  <ItemGroup>
    <Using Include="Eventuous" />
    <Using Include="Shouldly" />
    <Using Include="TUnit.Core" />
  </ItemGroup>
</Project>
